# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jpmccfg23-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://jpmccfgregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5cff9eeb4e97448bafe4d9b611445348 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9c8cde393f5c4a4398a57fc6281dc538 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jpmccfgregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5cff9eeb4e97448bafe4d9b611445348 }}/jpmccfgregistryfrontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jpmccfg23-frontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_209470fee2e54ecca8791d44aab5af14 }}
        images: 'jpmccfgregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5cff9eeb4e97448bafe4d9b611445348 }}/jpmccfgregistryfrontend:${{ github.sha }}'